### ISSUE TITLE
README-be betenni a specifikaciot.

### ISSUE THREAD

**Issue by hegyhati** [Teaching-projects/SZE-ProjektMunka2-2019-Liftszimulator#1]
A specifikacio rendben volt, README-ben legyen nyoma.

**Comment by lebbenszki** [comment]
Frissítve.

**Comment by hegyhati** [comment]
Ilyenkor legkozelebb a commit message-be irjatok bele, hogy close #1, es akkor rogton idelinkeli, es lehet ra kattintani.
